### PR TITLE
Problem with node 0.12 fixed and some updates

### PR DESCRIPTION
**Pull request by jlazevedo**
After trying to use smc with node version 0.12, I found that the code was no longer building.

I took the liberty to add some updates made at lavoiesl/osx-cpu-temp.

Please review. Thanks!
Best,

### CODE REVIEW

**Comment by mmarcon** [comment]
Does this still compile with 0.10? If not it's probably fine, but then it makes sense to [specify the engines](https://docs.npmjs.com/files/package.json#engines) in package.json.

**Comment by sebhildebrandt** [comment]
Hi, 
I managed to try out the pull request from @jlazevedo and this works fine also on all node4 and node5 versions. The thing is, that I cannot pull it via npm. Just asking, if you could merge the pull request and also publish it on npm (I guess this makes more sense as to create just another npm module). 
Thank you in advance!
Regards

**Comment by mmarcon** [comment]
@sebhildebrandt thanks for verifying. It's merged and published to npm.

**Comment by sebhildebrandt** [comment]
Thank you so much!! That was fast!
Appreciated!

Have a nice day!

**Pull request merged**
